spring.application.name=OmniTicket-Reservation-Service

# .env dosyasını properties dosyasıymış gibi yükle (Varsa)
spring.config.import=optional:file:./.env[.properties]

# PostgreSQL Bağlantısı
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB:omniticket}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate - Tabloları Otomatik Güncelle
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis Ayarı
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

# LOGLAMA VE KONSOL GÜZELLEŞTİRME
spring.output.ansi.enabled=ALWAYS

# Hibernate SQL çıktılarını güzelleştir
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.results=INFO

# Log formatı
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%5p) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}

# Scalar ve OpenAPI ayarları
scalar.enabled=true
scalar.url=/v3/api-docs

# Yeniden deneme mekanizmasını aktif et
spring.rabbitmq.listener.simple.retry.enabled=true
# Maksimum 3 deneme yap (ilk deneme + 2 tekrar)
spring.rabbitmq.listener.simple.retry.max-retries=3
# Denemeler arası bekleme süresi (1 saniye)
spring.rabbitmq.listener.simple.retry.initial-interval=1000ms
# 3 deneme sonunda hala hata varsa mesajı reddet (böylece DLQ'ya gider)
spring.rabbitmq.listener.simple.retry.multiplier=1.0
spring.rabbitmq.listener.simple.default-requeue-rejected=false

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=3518ee86eec883
spring.mail.password=d644c18d40af4e
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true