spring.application.name=OmniTicket-Reservation-Service

# .env dosyasını içeri aktarma (Docker dışında yerel test için)
spring.config.import=optional:file:./.env[.properties]

# Veritabanı Ayarları (Dinamik ve Güvenli) 
# Docker'da DB_HOST=postgres, yerelde DB_HOST=localhost olacak şekilde .env'den beslenir
spring.datasource.url=jdbc:postgresql://localhost:5432/omniticket
spring.datasource.username=${POSTGRES_USER:omniticket_db}
spring.datasource.password=${POSTGRES_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
# Hibernate Dialect silindi (Otomatik tespit ediliyor)

# Redis Ayarları
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

# Log ve ANSI Ayarları (HP Victus ekranında renkli loglar iyidir )
spring.output.ansi.enabled=ALWAYS
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.results=INFO
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%5p) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}

# API Dökümantasyon (Scalar)
scalar.enabled=true
scalar.url=/v3/api-docs

# RabbitMQ Retry Mekanizması
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=1000ms
spring.rabbitmq.listener.simple.retry.multiplier=1.0
spring.rabbitmq.listener.simple.default-requeue-rejected=false

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Monitoring (Prometheus için hazır) 
management.endpoints.web.exposure.include=health,prometheus
management.metrics.tags.application=omniticket-service